# frozen_string_literal: true

require "test_helper"
require "vips"
require "yaml"

class ImageLab::AI::U2netpPreprocessorTest < ActiveSupport::TestCase
  REFERENCE_PATH = Rails.root.join("test/fixtures/files/u2netp/preprocessing_reference.yml").freeze

  test "matches selected values generated by pinned upstream preprocessing" do
    tensor = ImageLab::AI::U2netp::Preprocessor.call(reference_image)

    assert_equal reference.fetch("tensor_shape"), tensor.shape
    reference.fetch("samples").each do |sample|
      assert_in_delta sample.fetch("value"), tensor.at(*sample.fetch("index")), 1e-5
    end
  end

  test "uses square aspect-distorting geometry and NCHW channel order" do
    tensor = ImageLab::AI::U2netp::Preprocessor.call(asymmetric_rgb_image)

    assert_equal [ 1, 3, 320, 320 ], tensor.shape
    assert_operator tensor.at(0, 0, 0, 0), :>, tensor.at(0, 2, 0, 0)
  end

  test "replicates grayscale before channel normalization" do
    tensor = ImageLab::AI::U2netp::Preprocessor.call(grayscale_image)
    normalized_channels = [
      tensor.at(0, 0, 0, 0) * 0.229 + 0.485,
      tensor.at(0, 1, 0, 0) * 0.224 + 0.456,
      tensor.at(0, 2, 0, 0) * 0.225 + 0.406
    ]

    assert_in_delta normalized_channels.first, normalized_channels.second, 1e-5
    assert_in_delta normalized_channels.first, normalized_channels.third, 1e-5
  end

  test "ignores alpha without mutating the source image" do
    source = rgba_image(alpha: 128)
    before = source.write_to_memory

    original_alpha = ImageLab::AI::U2netp::Preprocessor.call(source)
    ignored_alpha = ImageLab::AI::U2netp::Preprocessor.call(rgba_image(alpha: 0))

    assert_equal before, source.write_to_memory
    assert_equal original_alpha.values, ignored_alpha.values
  end

  test "fails closed for a black image and an incompatible manifest shape" do
    error = assert_raises(ImageLab::Errors::AiUnavailable) do
      ImageLab::AI::U2netp::Preprocessor.call(black_image)
    end
    assert_equal "AI model is unavailable", error.message

    manifest = Struct.new(:input_shape).new([ 1, 3, 321, 320 ])
    assert_raises(ImageLab::Errors::AiUnavailable) do
      ImageLab::AI::U2netp::Preprocessor.call(reference_image, manifest: manifest)
    end
  end

  private

  def reference
    @reference ||= YAML.safe_load_file(REFERENCE_PATH, permitted_classes: [], aliases: false)
  end

  def reference_image
    pixels = Array.new(320 * 320 * 3) do |index|
      row, remainder = index.divmod(320 * 3)
      column, channel = remainder.divmod(3)
      (row * 5 + column * 3 + channel * 17) % 256
    end
    Vips::Image.new_from_memory(pixels.pack("C*"), 320, 320, 3, :uchar).copy(interpretation: :srgb)
  end

  def asymmetric_rgb_image
    pixels = [ 255, 0, 0 ] + Array.new(2 * 4 * 3 - 3, 0)
    Vips::Image.new_from_memory(pixels.pack("C*"), 2, 4, 3, :uchar).copy(interpretation: :srgb)
  end

  def grayscale_image
    Vips::Image.new_from_memory([ 128 ].pack("C*"), 1, 1, 1, :uchar).copy(interpretation: :b_w)
  end

  def rgba_image(alpha:)
    Vips::Image.new_from_memory([ 100, 150, 200, alpha ].pack("C*"), 1, 1, 4, :uchar).copy(interpretation: :srgb)
  end

  def black_image
    Vips::Image.new_from_memory([ 0, 0, 0 ].pack("C*"), 1, 1, 3, :uchar).copy(interpretation: :srgb)
  end
end
